study: "all"
data_root: "../data"
outdir: "../analysis"
work_root: "work"
nextflow_work_root: ".nextflow_work"
slurm_partition: "low_p"
cache_mode: "deep"
python3_bin: "python3"
python2_bin: "python2.7"
plink_bin: "plink"
