#!/usr/bin/env python3
"""Generate conda lock files (linux-64, explicit URLs + md5) from environment .yml files.

Every pipeline environment is created from a lock file, so a fresh clone gets exactly
the same packages as the reference run, with no dependency solving on the cluster.
The solve is done "as of" --cutoff (pixi's exclude-newer): every package in the lock,
including indirect dependencies, was published on or before that date. Version pins
alone are not enough: maintainers rebuild the same version against newer dependencies
(e.g. minimac4 4.1.6 in Aug 2026, which then pulls in bcftools/htslib 1.24).

Usage (maintainers; needs pixi, https://pixi.sh, and internet access; any platform):
    python3 src/misc/make_env_locks.py                  # every environment
    python3 src/misc/make_env_locks.py pipeline_stage2/envs/prep_reference.yml
Writes <env>.lock.txt next to each <env>.yml. Commit both. Change --cutoff only when
deliberately moving the whole pipeline to newer software, then re-validate a run.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_CUTOFF = "2026-06-17"  # the June 2026 run
PLATFORM = "linux-64"
GLIBC = "2.28"
SKIP = {"documentation.yml", "mkdocs.yml"}


def default_envs() -> list[Path]:
    envs = sorted(REPO.glob("pipeline_stage*/envs/*.yml")) + sorted((REPO / "envs").glob("*.yml"))
    return [p for p in envs if p.name not in SKIP]


def parse_env(path: Path) -> tuple[list[str], list[str]]:
    """Return (channels, dependencies) from a simple conda environment .yml."""
    channels, deps, section = [], [], None
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if not line.startswith(" "):
            section = line.split(":", 1)[0].strip()
            continue
        item = line.strip()
        if item.startswith("- "):
            value = item[2:].strip()
            if section == "channels" and value != "nodefaults":
                channels.append(value)
            elif section == "dependencies":
                deps.append(value)
    return channels, deps


def pixi_spec(dep: str) -> tuple[str, str]:
    """conda spec -> (name, pixi version spec). conda's name=1.21 means 1.21.*"""
    match = re.fullmatch(r"([A-Za-z0-9_.\-]+)\s*(.*)", dep)
    name, rest = match.group(1), match.group(2).strip()
    if not rest:
        return name, "*"
    if rest.startswith("=") and not rest.startswith("=="):
        return name, rest[1:] + ".*"
    return name, rest


def lock_env(yml: Path, cutoff: str, pixi: str) -> Path:
    channels, deps = parse_env(yml)
    specs = [pixi_spec(d) for d in deps]
    manifest = "\n".join([
        "[workspace]",
        'name = "lockgen"',
        "channels = [" + ", ".join(f'"{c}"' for c in channels) + "]",
        f'platforms = ["{PLATFORM}"]',
        f'exclude-newer = "{cutoff}"',
        "",
        "[system-requirements]",
        f'libc = "{GLIBC}"',
        "",
        "[dependencies]",
    ] + [f'"{name}" = "{version}"' for name, version in specs]) + "\n"
    with tempfile.TemporaryDirectory() as tmp:
        (Path(tmp) / "pixi.toml").write_text(manifest)
        for cmd in (["lock"], ["workspace", "export", "conda-explicit-spec", "out"]):
            result = subprocess.run([pixi, *cmd, "--manifest-path", str(Path(tmp) / "pixi.toml")],
                                    cwd=tmp, capture_output=True, text=True)
            if result.returncode != 0:
                sys.exit(f"ERROR: {yml.name}: pixi {' '.join(cmd)} failed:\n{result.stderr[-3000:]}")
        exported = (Path(tmp) / "out" / f"default_{PLATFORM}_conda_spec.txt").read_text()
    body = [line for line in exported.splitlines() if line.startswith("https://")]
    lock = yml.with_suffix(".lock.txt")
    lock.write_text("\n".join([
        f"# Generated by src/misc/make_env_locks.py from {yml.name}; do not edit by hand.",
        f"# Requested: {' '.join(deps)} | packages published by {cutoff}",
        f"# platform: {PLATFORM}",
        "@EXPLICIT",
    ] + body) + "\n")
    return lock


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("envs", nargs="*", type=Path, help="environment .yml files (default: all)")
    parser.add_argument("--cutoff", default=DEFAULT_CUTOFF, help="solve as of this date (YYYY-MM-DD)")
    args = parser.parse_args()
    pixi = os.environ.get("PIXI") or shutil.which("pixi")
    if not pixi:
        sys.exit("ERROR: pixi not found; install it (https://pixi.sh) or set PIXI=/path/to/pixi")

    for yml in args.envs or default_envs():
        yml = yml.resolve()
        lock = lock_env(yml, args.cutoff, pixi)
        names = {re.split(r"[\s=<>!]", d)[0] for d in parse_env(yml)[1]}
        got = []
        for url in (l for l in lock.read_text().splitlines() if l.startswith("https://")):
            fn = url.rsplit("/", 1)[-1].split("#")[0]
            name, version, _build = re.sub(r"\.(conda|tar\.bz2)$", "", fn).rsplit("-", 2)
            if name in names:
                got.append(f"{name}={version}")
        print(f"{lock.relative_to(REPO)}: {sum(1 for l in lock.read_text().splitlines() if l.startswith('https://'))} packages | {' '.join(sorted(got))}")


if __name__ == "__main__":
    main()
